resource "harness_platform_roles" "shared_account" {
  identifier  = "shared_account"
  name        = "shared_account"
  description = "An example role managed by Terraform."
  tags        = concat(var.default_tags, ["Demo:true"])
  permissions = [
    # "ccm_anomalies_view",
    # "ccm_autoStoppingRule_delete",
    # "ccm_autoStoppingRule_edit",
    # "ccm_autoStoppingRule_view",
    # "ccm_budget_delete",
    # "ccm_budget_edit",
    # "ccm_budget_view",
    # "ccm_cloudAssetGovernanceEnforcement_delete",
    # "ccm_cloudAssetGovernanceEnforcement_edit",
    # "ccm_cloudAssetGovernanceEnforcement_view",
    # "ccm_cloudAssetGovernanceRule_delete",
    # "ccm_cloudAssetGovernanceRule_edit",
    # "ccm_cloudAssetGovernanceRule_execute",
    # "ccm_cloudAssetGovernanceRule_view",
    # "ccm_cloudAssetGovernanceRuleSet_delete",
    # "ccm_cloudAssetGovernanceRuleSet_edit",
    # "ccm_cloudAssetGovernanceRuleSet_view",
    # "ccm_commitmentOrchestrator_edit",
    # "ccm_commitmentOrchestrator_view",
    # "ccm_costCategory_delete",
    # "ccm_costCategory_edit",
    # "ccm_costCategory_view",
    # "ccm_currencyPreference_edit",
    # "ccm_currencyPreference_view",
    # "ccm_folder_delete",
    # "ccm_folder_edit",
    # "ccm_folder_view",
    # "ccm_loadBalancer_delete",
    # "ccm_loadBalancer_edit",
    # "ccm_loadBalancer_view",
    # "ccm_overview_view",
    # "ccm_perspective_delete",
    # "ccm_perspective_edit",
    # "ccm_perspective_view",
    # "ccm_recommendations_view",

    # "cet_agents_view",
    # "cet_criticalevent_create",
    # "cet_criticalevent_delete",
    # "cet_criticalevent_view",
    # "cet_token_create",
    # "cet_token_revoke",
    # "cet_token_view",

    # "chaos_chaosexperiment_delete",
    # "chaos_chaosexperiment_edit",
    # "chaos_chaosexperiment_execute",
    # "chaos_chaosexperiment_view",
    # "chaos_chaosgameday_delete",
    # "chaos_chaosgameday_edit",
    # "chaos_chaosgameday_view",
    # "chaos_chaoshub_delete",
    # "chaos_chaoshub_edit",
    # "chaos_chaoshub_view",
    # "chaos_chaosinfrastructure_delete",
    # "chaos_chaosinfrastructure_edit",
    # "chaos_chaosinfrastructure_view",
    # "chaos_chaossecuritygovernance_delete",
    # "chaos_chaossecuritygovernance_edit",
    # "chaos_chaossecuritygovernance_view",

    # "chi_downtime_delete",
    # "chi_downtime_edit",
    # "chi_downtime_view",
    # "chi_monitoredservice_delete",
    # "chi_monitoredservice_edit",
    # "chi_monitoredservice_toggle",
    # "chi_monitoredservice_view",
    # "chi_slo_delete",
    # "chi_slo_edit",
    # "chi_slo_view",

    # "code_repo_delete",
    # "code_repo_edit",
    # "code_repo_push",
    # "code_repo_reportCommitCheck",
    # "code_repo_view",

    # "core_account_edit",
    # "core_account_view",
    # "core_audit_view",
    # "core_authsetting_delete",
    # "core_authsetting_edit",
    # "core_authsetting_view",
    "core_connector_access",
    # "core_connector_delete",
    # "core_connector_edit",
    # "core_connector_view",
    # "core_dashboards_edit",
    # "core_dashboards_view",
    # "core_delegate_delete",
    # "core_delegate_edit",
    # "core_delegate_view",
    # "core_delegateconfiguration_delete",
    # "core_delegateconfiguration_edit",
    # "core_delegateconfiguration_view",
    # "core_deploymentfreeze_global",
    # "core_deploymentfreeze_manage",
    # "core_deploymentfreeze_override",
    # "core_environment_access",
    # "core_environment_delete",
    # "core_environment_edit",
    # "core_environment_rollback",
    # "core_environment_view",
    # "core_environmentgroup_access",
    # "core_environmentgroup_delete",
    # "core_environmentgroup_edit",
    # "core_environmentgroup_view",
    # "core_file_access",
    # "core_file_delete",
    # "core_file_edit",
    # "core_file_view",
    # "core_gitxWebhooks_delete",
    # "core_gitxWebhooks_edit",
    # "core_gitxWebhooks_view",
    # "core_governancePolicy_create",
    # "core_governancePolicy_delete",
    # "core_governancePolicy_edit",
    # "core_governancePolicy_view",
    # "core_governancePolicySets_create",
    # "core_governancePolicySets_delete",
    # "core_governancePolicySets_edit",
    # "core_governancePolicySets_evaluate",
    # "core_governancePolicySets_view",
    # "core_inputset_delete",
    # "core_inputset_edit",
    # "core_inputset_view",
    # "core_license_edit",
    # "core_license_view",
    # "core_organization_create",
    # "core_organization_delete",
    # "core_organization_edit",
    # "core_organization_view",
    # "core_pipeline_delete",
    # "core_pipeline_edit",
    # "core_pipeline_execute",
    # "core_pipeline_view",
    # "core_project_create",
    # "core_project_delete",
    # "core_project_edit",
    # "core_project_view",
    # "core_resourcegroup_delete",
    # "core_resourcegroup_edit",
    # "core_resourcegroup_view",
    # "core_role_delete",
    # "core_role_edit",
    # "core_role_view",
    "core_secret_access",
    # "core_secret_delete",
    # "core_secret_edit",
    # "core_secret_view",
    # "core_service_access",
    # "core_service_delete",
    # "core_service_edit",
    # "core_service_view",
    # "core_serviceaccount_delete",
    # "core_serviceaccount_edit",
    # "core_serviceaccount_list",
    # "core_serviceaccount_manageapikey",
    # "core_serviceaccount_view",
    # "core_setting_edit",
    # "core_setting_view",
    # "core_smtp_delete",
    # "core_smtp_edit",
    # "core_smtp_view",
    # "core_streamingDestination_delete",
    # "core_streamingDestination_edit",
    # "core_streamingDestination_view",
    "core_template_access",
    # "core_template_copy",
    # "core_template_delete",
    # "core_template_edit",
    # "core_template_view",
    # "core_user_invite",
    # "core_user_manage",
    # "core_user_view",
    # "core_usergroup_manage",
    # "core_usergroup_view",
    # "core_variable_delete",
    # "core_variable_edit",
    # "core_variable_view",

    # "ff_environment_apiKeyCreate",
    # "ff_environment_apiKeyDelete",
    # "ff_environment_apiKeyView",
    # "ff_environment_edit",
    # "ff_environment_targetGroupEdit",
    # "ff_environment_view",
    # "ff_featureflag_delete",
    # "ff_featureflag_edit",
    # "ff_featureflag_toggle",
    # "ff_featureflag_view",
    # "ff_target_view",
    # "ff_targetgroup_delete",
    # "ff_targetgroup_edit",
    # "ff_targetgroup_view",

    # "gitops_agent_delete",
    # "gitops_agent_edit",
    # "gitops_agent_view",
    # "gitops_application_delete",
    # "gitops_application_edit",
    # "gitops_application_sync",
    # "gitops_application_view",
    # "gitops_cert_delete",
    # "gitops_cert_edit",
    # "gitops_cert_view",
    # "gitops_cluster_delete",
    # "gitops_cluster_edit",
    # "gitops_cluster_view",
    # "gitops_gpgkey_delete",
    # "gitops_gpgkey_edit",
    # "gitops_gpgkey_view",
    # "gitops_repository_delete",
    # "gitops_repository_edit",
    # "gitops_repository_view",

    # "iac_workspace_accessstate",
    # "iac_workspace_approve",
    # "iac_workspace_delete",
    # "iac_workspace_deletevariable",
    # "iac_workspace_edit",
    # "iac_workspace_editvariable",
    # "iac_workspace_view",

    # "idp_advancedconfiguration_delete",
    # "idp_advancedconfiguration_edit",
    # "idp_advancedconfiguration_view",
    # "idp_catalogaccesspolicy_create",
    # "idp_catalogaccesspolicy_delete",
    # "idp_catalogaccesspolicy_edit",
    # "idp_catalogaccesspolicy_view",
    # "idp_integration_create",
    # "idp_integration_delete",
    # "idp_integration_edit",
    # "idp_integration_view",
    # "idp_layout_edit",
    # "idp_layout_view",
    # "idp_plugin_delete",
    # "idp_plugin_edit",
    # "idp_plugin_toggle",
    # "idp_plugin_view",
    # "idp_scorecard_delete",
    # "idp_scorecard_edit",
    # "idp_scorecard_view",

    # "servicediscovery_networkmap_create",
    # "servicediscovery_networkmap_delete",
    # "servicediscovery_networkmap_edit",
    # "servicediscovery_networkmap_view",

    # "ssca_enforcementexemption_delete",
    # "ssca_enforcementexemption_edit",
    # "ssca_enforcementexemption_review",
    # "ssca_enforcementexemption_view",
    # "ssca_remediationtracker_close",
    # "ssca_remediationtracker_edit",
    # "ssca_remediationtracker_view",

    # "sto_exemption_approve",
    # "sto_exemption_create",
    # "sto_exemption_view",
    # "sto_issue_view",
    # "sto_scan_view",
    # "sto_testtarget_edit",
    # "sto_testtarget_view",
    # "sto_ticket_delete",
    # "sto_ticket_edit",
    # "sto_ticket_view",
  ]
  allowed_scope_levels = ["account"]
}
resource "harness_platform_roles" "developer" {
  identifier  = "developer"
  name        = "developer"
  description = "An example role managed by Terraform."
  tags        = concat(var.default_tags, ["Demo:true"])
  permissions = [
    # "ccm_anomalies_view",
    # "ccm_autoStoppingRule_delete",
    # "ccm_autoStoppingRule_edit",
    # "ccm_autoStoppingRule_view",
    # "ccm_budget_delete",
    # "ccm_budget_edit",
    # "ccm_budget_view",
    # "ccm_cloudAssetGovernanceEnforcement_delete",
    # "ccm_cloudAssetGovernanceEnforcement_edit",
    # "ccm_cloudAssetGovernanceEnforcement_view",
    # "ccm_cloudAssetGovernanceRule_delete",
    # "ccm_cloudAssetGovernanceRule_edit",
    # "ccm_cloudAssetGovernanceRule_execute",
    # "ccm_cloudAssetGovernanceRule_view",
    # "ccm_cloudAssetGovernanceRuleSet_delete",
    # "ccm_cloudAssetGovernanceRuleSet_edit",
    # "ccm_cloudAssetGovernanceRuleSet_view",
    # "ccm_commitmentOrchestrator_edit",
    # "ccm_commitmentOrchestrator_view",
    # "ccm_costCategory_delete",
    # "ccm_costCategory_edit",
    # "ccm_costCategory_view",
    # "ccm_currencyPreference_edit",
    # "ccm_currencyPreference_view",
    # "ccm_folder_delete",
    # "ccm_folder_edit",
    # "ccm_folder_view",
    # "ccm_loadBalancer_delete",
    # "ccm_loadBalancer_edit",
    # "ccm_loadBalancer_view",
    # "ccm_overview_view",
    # "ccm_perspective_delete",
    # "ccm_perspective_edit",
    # "ccm_perspective_view",
    # "ccm_recommendations_view",

    # "cet_agents_view",
    # "cet_criticalevent_create",
    # "cet_criticalevent_delete",
    # "cet_criticalevent_view",
    # "cet_token_create",
    # "cet_token_revoke",
    # "cet_token_view",

    # "chaos_chaosexperiment_delete",
    # "chaos_chaosexperiment_edit",
    # "chaos_chaosexperiment_execute",
    "chaos_chaosexperiment_view",
    # "chaos_chaosgameday_delete",
    # "chaos_chaosgameday_edit",
    "chaos_chaosgameday_view",
    # "chaos_chaoshub_delete",
    # "chaos_chaoshub_edit",
    "chaos_chaoshub_view",
    # "chaos_chaosinfrastructure_delete",
    # "chaos_chaosinfrastructure_edit",
    "chaos_chaosinfrastructure_view",
    # "chaos_chaossecuritygovernance_delete",
    # "chaos_chaossecuritygovernance_edit",
    "chaos_chaossecuritygovernance_view",

    # "chi_downtime_delete",
    # "chi_downtime_edit",
    # "chi_downtime_view",
    # "chi_monitoredservice_delete",
    # "chi_monitoredservice_edit",
    # "chi_monitoredservice_toggle",
    # "chi_monitoredservice_view",
    # "chi_slo_delete",
    # "chi_slo_edit",
    # "chi_slo_view",

    # "code_repo_delete",
    # "code_repo_edit",
    # "code_repo_push",
    # "code_repo_reportCommitCheck",
    # "code_repo_view",

    # "core_account_edit",
    # "core_account_view",
    # "core_audit_view",
    # "core_authsetting_delete",
    # "core_authsetting_edit",
    # "core_authsetting_view",
    "core_connector_access",
    # "core_connector_delete",
    # "core_connector_edit",
    # "core_connector_view",
    # "core_dashboards_edit",
    # "core_dashboards_view",
    # "core_delegate_delete",
    # "core_delegate_edit",
    # "core_delegate_view",
    # "core_delegateconfiguration_delete",
    # "core_delegateconfiguration_edit",
    # "core_delegateconfiguration_view",
    # "core_deploymentfreeze_global",
    # "core_deploymentfreeze_manage",
    # "core_deploymentfreeze_override",
    "core_environment_access",
    # "core_environment_delete",
    # "core_environment_edit",
    # "core_environment_rollback",
    # "core_environment_view",
    "core_environmentgroup_access",
    # "core_environmentgroup_delete",
    # "core_environmentgroup_edit",
    # "core_environmentgroup_view",
    "core_file_access",
    # "core_file_delete",
    # "core_file_edit",
    # "core_file_view",
    # "core_gitxWebhooks_delete",
    # "core_gitxWebhooks_edit",
    # "core_gitxWebhooks_view",
    # "core_governancePolicy_create",
    # "core_governancePolicy_delete",
    # "core_governancePolicy_edit",
    # "core_governancePolicy_view",
    # "core_governancePolicySets_create",
    # "core_governancePolicySets_delete",
    # "core_governancePolicySets_edit",
    # "core_governancePolicySets_evaluate",
    # "core_governancePolicySets_view",
    # "core_inputset_delete",
    # "core_inputset_edit",
    # "core_inputset_view",
    # "core_license_edit",
    # "core_license_view",
    # "core_organization_create",
    # "core_organization_delete",
    # "core_organization_edit",
    "core_organization_view",
    # "core_pipeline_delete",
    # "core_pipeline_edit",
    "core_pipeline_execute",
    "core_pipeline_view",
    # "core_project_create",
    # "core_project_delete",
    # "core_project_edit",
    "core_project_view",
    # "core_resourcegroup_delete",
    # "core_resourcegroup_edit",
    # "core_resourcegroup_view",
    # "core_role_delete",
    # "core_role_edit",
    # "core_role_view",
    "core_secret_access",
    # "core_secret_delete",
    # "core_secret_edit",
    # "core_secret_view",
    "core_service_access",
    # "core_service_delete",
    # "core_service_edit",
    # "core_service_view",
    # "core_serviceaccount_delete",
    # "core_serviceaccount_edit",
    # "core_serviceaccount_list",
    # "core_serviceaccount_manageapikey",
    # "core_serviceaccount_view",
    # "core_setting_edit",
    # "core_setting_view",
    # "core_smtp_delete",
    # "core_smtp_edit",
    # "core_smtp_view",
    # "core_streamingDestination_delete",
    # "core_streamingDestination_edit",
    # "core_streamingDestination_view",
    "core_template_access",
    # "core_template_copy",
    # "core_template_delete",
    # "core_template_edit",
    # "core_template_view",
    # "core_user_invite",
    # "core_user_manage",
    # "core_user_view",
    # "core_usergroup_manage",
    # "core_usergroup_view",
    # "core_variable_delete",
    # "core_variable_edit",
    # "core_variable_view",

    # "ff_environment_apiKeyCreate",
    # "ff_environment_apiKeyDelete",
    "ff_environment_apiKeyView",
    # "ff_environment_edit",
    # "ff_environment_targetGroupEdit",
    "ff_environment_view",
    # "ff_featureflag_delete",
    # "ff_featureflag_edit",
    # "ff_featureflag_toggle",
    "ff_featureflag_view",
    "ff_target_view",
    # "ff_targetgroup_delete",
    # "ff_targetgroup_edit",
    "ff_targetgroup_view",

    # "gitops_agent_delete",
    # "gitops_agent_edit",
    # "gitops_agent_view",
    # "gitops_application_delete",
    # "gitops_application_edit",
    # "gitops_application_sync",
    # "gitops_application_view",
    # "gitops_cert_delete",
    # "gitops_cert_edit",
    # "gitops_cert_view",
    # "gitops_cluster_delete",
    # "gitops_cluster_edit",
    # "gitops_cluster_view",
    # "gitops_gpgkey_delete",
    # "gitops_gpgkey_edit",
    # "gitops_gpgkey_view",
    # "gitops_repository_delete",
    # "gitops_repository_edit",
    # "gitops_repository_view",

    # "iac_workspace_accessstate",
    # "iac_workspace_approve",
    # "iac_workspace_delete",
    # "iac_workspace_deletevariable",
    # "iac_workspace_edit",
    # "iac_workspace_editvariable",
    # "iac_workspace_view",

    # "idp_advancedconfiguration_delete",
    # "idp_advancedconfiguration_edit",
    # "idp_advancedconfiguration_view",
    # "idp_catalogaccesspolicy_create",
    # "idp_catalogaccesspolicy_delete",
    # "idp_catalogaccesspolicy_edit",
    # "idp_catalogaccesspolicy_view",
    # "idp_integration_create",
    # "idp_integration_delete",
    # "idp_integration_edit",
    # "idp_integration_view",
    # "idp_layout_edit",
    # "idp_layout_view",
    # "idp_plugin_delete",
    # "idp_plugin_edit",
    # "idp_plugin_toggle",
    # "idp_plugin_view",
    # "idp_scorecard_delete",
    # "idp_scorecard_edit",
    # "idp_scorecard_view",

    # "servicediscovery_networkmap_create",
    # "servicediscovery_networkmap_delete",
    # "servicediscovery_networkmap_edit",
    # "servicediscovery_networkmap_view",

    # "ssca_enforcementexemption_delete",
    # "ssca_enforcementexemption_edit",
    # "ssca_enforcementexemption_review",
    # "ssca_enforcementexemption_view",
    # "ssca_remediationtracker_close",
    # "ssca_remediationtracker_edit",
    # "ssca_remediationtracker_view",

    # "sto_exemption_approve",
    "sto_exemption_create",
    "sto_exemption_view",
    "sto_issue_view",
    "sto_scan_view",
    # "sto_testtarget_edit",
    "sto_testtarget_view",
    # "sto_ticket_delete",
    # "sto_ticket_edit",
    "sto_ticket_view",
  ]
  allowed_scope_levels = ["account"]
}

resource "harness_platform_roles" "admin" {
  identifier  = "admin"
  name        = "admin"
  description = "An example role managed by Terraform."
  tags        = concat(var.default_tags, ["Demo:true"])
  permissions = [
    # "ccm_anomalies_view",
    # "ccm_autoStoppingRule_delete",
    # "ccm_autoStoppingRule_edit",
    # "ccm_autoStoppingRule_view",
    # "ccm_budget_delete",
    # "ccm_budget_edit",
    # "ccm_budget_view",
    # "ccm_cloudAssetGovernanceEnforcement_delete",
    # "ccm_cloudAssetGovernanceEnforcement_edit",
    # "ccm_cloudAssetGovernanceEnforcement_view",
    # "ccm_cloudAssetGovernanceRule_delete",
    # "ccm_cloudAssetGovernanceRule_edit",
    # "ccm_cloudAssetGovernanceRule_execute",
    # "ccm_cloudAssetGovernanceRule_view",
    # "ccm_cloudAssetGovernanceRuleSet_delete",
    # "ccm_cloudAssetGovernanceRuleSet_edit",
    # "ccm_cloudAssetGovernanceRuleSet_view",
    # "ccm_commitmentOrchestrator_edit",
    # "ccm_commitmentOrchestrator_view",
    # "ccm_costCategory_delete",
    # "ccm_costCategory_edit",
    # "ccm_costCategory_view",
    # "ccm_currencyPreference_edit",
    # "ccm_currencyPreference_view",
    # "ccm_folder_delete",
    # "ccm_folder_edit",
    # "ccm_folder_view",
    # "ccm_loadBalancer_delete",
    # "ccm_loadBalancer_edit",
    # "ccm_loadBalancer_view",
    # "ccm_overview_view",
    # "ccm_perspective_delete",
    # "ccm_perspective_edit",
    # "ccm_perspective_view",
    # "ccm_recommendations_view",

    # "cet_agents_view",
    # "cet_criticalevent_create",
    # "cet_criticalevent_delete",
    # "cet_criticalevent_view",
    # "cet_token_create",
    # "cet_token_revoke",
    # "cet_token_view",

    "chaos_chaosexperiment_delete",
    "chaos_chaosexperiment_edit",
    "chaos_chaosexperiment_execute",
    "chaos_chaosexperiment_view",
    "chaos_chaosgameday_delete",
    "chaos_chaosgameday_edit",
    "chaos_chaosgameday_view",
    "chaos_chaoshub_delete",
    "chaos_chaoshub_edit",
    "chaos_chaoshub_view",
    "chaos_chaosinfrastructure_delete",
    "chaos_chaosinfrastructure_edit",
    "chaos_chaosinfrastructure_view",
    "chaos_chaossecuritygovernance_delete",
    "chaos_chaossecuritygovernance_edit",
    "chaos_chaossecuritygovernance_view",

    # "chi_downtime_delete",
    # "chi_downtime_edit",
    # "chi_downtime_view",
    # "chi_monitoredservice_delete",
    # "chi_monitoredservice_edit",
    # "chi_monitoredservice_toggle",
    # "chi_monitoredservice_view",
    # "chi_slo_delete",
    # "chi_slo_edit",
    # "chi_slo_view",

    # "code_repo_delete",
    # "code_repo_edit",
    # "code_repo_push",
    # "code_repo_reportCommitCheck",
    # "code_repo_view",

    # "core_account_edit",
    # "core_account_view",
    # "core_audit_view",
    # "core_authsetting_delete",
    # "core_authsetting_edit",
    # "core_authsetting_view",
    "core_connector_access",
    "core_connector_delete",
    "core_connector_edit",
    "core_connector_view",
    # "core_dashboards_edit",
    # "core_dashboards_view",
    # "core_delegate_delete",
    # "core_delegate_edit",
    # "core_delegate_view",
    # "core_delegateconfiguration_delete",
    # "core_delegateconfiguration_edit",
    # "core_delegateconfiguration_view",
    # "core_deploymentfreeze_global",
    # "core_deploymentfreeze_manage",
    # "core_deploymentfreeze_override",
    "core_environment_access",
    "core_environment_delete",
    "core_environment_edit",
    "core_environment_rollback",
    "core_environment_view",
    "core_environmentgroup_access",
    "core_environmentgroup_delete",
    "core_environmentgroup_edit",
    "core_environmentgroup_view",
    "core_file_access",
    "core_file_delete",
    "core_file_edit",
    "core_file_view",
    # "core_gitxWebhooks_delete",
    # "core_gitxWebhooks_edit",
    # "core_gitxWebhooks_view",
    # "core_governancePolicy_create",
    # "core_governancePolicy_delete",
    # "core_governancePolicy_edit",
    # "core_governancePolicy_view",
    # "core_governancePolicySets_create",
    # "core_governancePolicySets_delete",
    # "core_governancePolicySets_edit",
    # "core_governancePolicySets_evaluate",
    # "core_governancePolicySets_view",
    "core_inputset_delete",
    "core_inputset_edit",
    "core_inputset_view",
    # "core_license_edit",
    # "core_license_view",
    # "core_organization_create",
    # "core_organization_delete",
    # "core_organization_edit",
    "core_organization_view",
    "core_pipeline_delete",
    "core_pipeline_edit",
    # "core_pipeline_execute",
    "core_pipeline_view",
    # "core_project_create",
    # "core_project_delete",
    # "core_project_edit",
    "core_project_view",
    # "core_resourcegroup_delete",
    # "core_resourcegroup_edit",
    # "core_resourcegroup_view",
    # "core_role_delete",
    # "core_role_edit",
    # "core_role_view",
    "core_secret_access",
    "core_secret_delete",
    "core_secret_edit",
    "core_secret_view",
    "core_service_access",
    "core_service_delete",
    "core_service_edit",
    "core_service_view",
    # "core_serviceaccount_delete",
    # "core_serviceaccount_edit",
    # "core_serviceaccount_list",
    # "core_serviceaccount_manageapikey",
    # "core_serviceaccount_view",
    # "core_setting_edit",
    # "core_setting_view",
    # "core_smtp_delete",
    # "core_smtp_edit",
    # "core_smtp_view",
    # "core_streamingDestination_delete",
    # "core_streamingDestination_edit",
    # "core_streamingDestination_view",
    "core_template_access",
    "core_template_copy",
    "core_template_delete",
    "core_template_edit",
    "core_template_view",
    # "core_user_invite",
    # "core_user_manage",
    # "core_user_view",
    # "core_usergroup_manage",
    # "core_usergroup_view",
    "core_variable_delete",
    "core_variable_edit",
    "core_variable_view",

    "ff_environment_apiKeyCreate",
    "ff_environment_apiKeyDelete",
    "ff_environment_apiKeyView",
    "ff_environment_edit",
    "ff_environment_targetGroupEdit",
    "ff_environment_view",
    "ff_featureflag_delete",
    "ff_featureflag_edit",
    # "ff_featureflag_toggle",
    "ff_featureflag_view",
    "ff_target_view",
    "ff_targetgroup_delete",
    "ff_targetgroup_edit",
    "ff_targetgroup_view",

    # "gitops_agent_delete",
    # "gitops_agent_edit",
    # "gitops_agent_view",
    # "gitops_application_delete",
    # "gitops_application_edit",
    # "gitops_application_sync",
    # "gitops_application_view",
    # "gitops_cert_delete",
    # "gitops_cert_edit",
    # "gitops_cert_view",
    # "gitops_cluster_delete",
    # "gitops_cluster_edit",
    # "gitops_cluster_view",
    # "gitops_gpgkey_delete",
    # "gitops_gpgkey_edit",
    # "gitops_gpgkey_view",
    # "gitops_repository_delete",
    # "gitops_repository_edit",
    # "gitops_repository_view",

    # "iac_workspace_accessstate",
    # "iac_workspace_approve",
    # "iac_workspace_delete",
    # "iac_workspace_deletevariable",
    # "iac_workspace_edit",
    # "iac_workspace_editvariable",
    # "iac_workspace_view",

    # "idp_advancedconfiguration_delete",
    # "idp_advancedconfiguration_edit",
    # "idp_advancedconfiguration_view",
    # "idp_catalogaccesspolicy_create",
    # "idp_catalogaccesspolicy_delete",
    # "idp_catalogaccesspolicy_edit",
    # "idp_catalogaccesspolicy_view",
    # "idp_integration_create",
    # "idp_integration_delete",
    # "idp_integration_edit",
    # "idp_integration_view",
    # "idp_layout_edit",
    # "idp_layout_view",
    # "idp_plugin_delete",
    # "idp_plugin_edit",
    # "idp_plugin_toggle",
    # "idp_plugin_view",
    # "idp_scorecard_delete",
    # "idp_scorecard_edit",
    # "idp_scorecard_view",

    # "servicediscovery_networkmap_create",
    # "servicediscovery_networkmap_delete",
    # "servicediscovery_networkmap_edit",
    # "servicediscovery_networkmap_view",

    # "ssca_enforcementexemption_delete",
    # "ssca_enforcementexemption_edit",
    # "ssca_enforcementexemption_review",
    # "ssca_enforcementexemption_view",
    # "ssca_remediationtracker_close",
    # "ssca_remediationtracker_edit",
    # "ssca_remediationtracker_view",

    # "sto_exemption_approve",
    # "sto_exemption_create",
    "sto_exemption_view",
    "sto_issue_view",
    "sto_scan_view",
    # "sto_testtarget_edit",
    "sto_testtarget_view",
    # "sto_ticket_delete",
    # "sto_ticket_edit",
    "sto_ticket_view",
  ]
  allowed_scope_levels = ["account"]
}

resource "harness_platform_roles" "platform_engineer" {
  identifier  = "platform_engineer"
  name        = "platform-engineer"
  description = "An example role managed by Terraform."
  tags        = concat(var.default_tags, ["Demo:true"])
  permissions = [
    # "ccm_anomalies_view",
    # "ccm_autoStoppingRule_delete",
    # "ccm_autoStoppingRule_edit",
    # "ccm_autoStoppingRule_view",
    # "ccm_budget_delete",
    # "ccm_budget_edit",
    # "ccm_budget_view",
    # "ccm_cloudAssetGovernanceEnforcement_delete",
    # "ccm_cloudAssetGovernanceEnforcement_edit",
    # "ccm_cloudAssetGovernanceEnforcement_view",
    # "ccm_cloudAssetGovernanceRule_delete",
    # "ccm_cloudAssetGovernanceRule_edit",
    # "ccm_cloudAssetGovernanceRule_execute",
    # "ccm_cloudAssetGovernanceRule_view",
    # "ccm_cloudAssetGovernanceRuleSet_delete",
    # "ccm_cloudAssetGovernanceRuleSet_edit",
    # "ccm_cloudAssetGovernanceRuleSet_view",
    # "ccm_commitmentOrchestrator_edit",
    # "ccm_commitmentOrchestrator_view",
    # "ccm_costCategory_delete",
    # "ccm_costCategory_edit",
    # "ccm_costCategory_view",
    # "ccm_currencyPreference_edit",
    # "ccm_currencyPreference_view",
    # "ccm_folder_delete",
    # "ccm_folder_edit",
    # "ccm_folder_view",
    # "ccm_loadBalancer_delete",
    # "ccm_loadBalancer_edit",
    # "ccm_loadBalancer_view",
    # "ccm_overview_view",
    # "ccm_perspective_delete",
    # "ccm_perspective_edit",
    # "ccm_perspective_view",
    # "ccm_recommendations_view",

    # "cet_agents_view",
    # "cet_criticalevent_create",
    # "cet_criticalevent_delete",
    # "cet_criticalevent_view",
    # "cet_token_create",
    # "cet_token_revoke",
    # "cet_token_view",

    # "chaos_chaosexperiment_delete",
    # "chaos_chaosexperiment_edit",
    # "chaos_chaosexperiment_execute",
    # "chaos_chaosexperiment_view",
    # "chaos_chaosgameday_delete",
    # "chaos_chaosgameday_edit",
    # "chaos_chaosgameday_view",
    # "chaos_chaoshub_delete",
    # "chaos_chaoshub_edit",
    # "chaos_chaoshub_view",
    # "chaos_chaosinfrastructure_delete",
    # "chaos_chaosinfrastructure_edit",
    # "chaos_chaosinfrastructure_view",
    # "chaos_chaossecuritygovernance_delete",
    # "chaos_chaossecuritygovernance_edit",
    # "chaos_chaossecuritygovernance_view",

    # "chi_downtime_delete",
    # "chi_downtime_edit",
    # "chi_downtime_view",
    # "chi_monitoredservice_delete",
    # "chi_monitoredservice_edit",
    # "chi_monitoredservice_toggle",
    # "chi_monitoredservice_view",
    # "chi_slo_delete",
    # "chi_slo_edit",
    # "chi_slo_view",

    # "code_repo_delete",
    # "code_repo_edit",
    # "code_repo_push",
    # "code_repo_reportCommitCheck",
    # "code_repo_view",

    # "core_account_edit",
    # "core_account_view",
    # "core_audit_view",
    # "core_authsetting_delete",
    # "core_authsetting_edit",
    # "core_authsetting_view",
    # "core_connector_access",
    # "core_connector_delete",
    # "core_connector_edit",
    # "core_connector_view",
    # "core_dashboards_edit",
    # "core_dashboards_view",
    # "core_delegate_delete",
    # "core_delegate_edit",
    # "core_delegate_view",
    # "core_delegateconfiguration_delete",
    # "core_delegateconfiguration_edit",
    # "core_delegateconfiguration_view",
    # "core_deploymentfreeze_global",
    # "core_deploymentfreeze_manage",
    # "core_deploymentfreeze_override",
    # "core_environment_access",
    # "core_environment_delete",
    # "core_environment_edit",
    # "core_environment_rollback",
    # "core_environment_view",
    # "core_environmentgroup_access",
    # "core_environmentgroup_delete",
    # "core_environmentgroup_edit",
    # "core_environmentgroup_view",
    # "core_file_access",
    # "core_file_delete",
    # "core_file_edit",
    # "core_file_view",
    # "core_gitxWebhooks_delete",
    # "core_gitxWebhooks_edit",
    # "core_gitxWebhooks_view",
    # "core_governancePolicy_create",
    # "core_governancePolicy_delete",
    # "core_governancePolicy_edit",
    # "core_governancePolicy_view",
    # "core_governancePolicySets_create",
    # "core_governancePolicySets_delete",
    # "core_governancePolicySets_edit",
    # "core_governancePolicySets_evaluate",
    # "core_governancePolicySets_view",
    # "core_inputset_delete",
    # "core_inputset_edit",
    # "core_inputset_view",
    # "core_license_edit",
    # "core_license_view",
    # "core_organization_create",
    # "core_organization_delete",
    # "core_organization_edit",
    "core_organization_view",
    # "core_pipeline_delete",
    # "core_pipeline_edit",
    # "core_pipeline_execute",
    # "core_pipeline_view",
    # "core_project_create",
    # "core_project_delete",
    # "core_project_edit",
    "core_project_view",
    # "core_resourcegroup_delete",
    # "core_resourcegroup_edit",
    # "core_resourcegroup_view",
    # "core_role_delete",
    # "core_role_edit",
    # "core_role_view",
    "core_secret_access",
    # "core_secret_delete",
    # "core_secret_edit",
    # "core_secret_view",
    # "core_service_access",
    # "core_service_delete",
    # "core_service_edit",
    # "core_service_view",
    # "core_serviceaccount_delete",
    # "core_serviceaccount_edit",
    # "core_serviceaccount_list",
    # "core_serviceaccount_manageapikey",
    # "core_serviceaccount_view",
    # "core_setting_edit",
    # "core_setting_view",
    # "core_smtp_delete",
    # "core_smtp_edit",
    # "core_smtp_view",
    # "core_streamingDestination_delete",
    # "core_streamingDestination_edit",
    # "core_streamingDestination_view",
    "core_template_access",
    # "core_template_copy",
    # "core_template_delete",
    # "core_template_edit",
    # "core_template_view",
    # "core_user_invite",
    # "core_user_manage",
    # "core_user_view",
    # "core_usergroup_manage",
    # "core_usergroup_view",
    # "core_variable_delete",
    # "core_variable_edit",
    # "core_variable_view",

    # "ff_environment_apiKeyCreate",
    # "ff_environment_apiKeyDelete",
    # "ff_environment_apiKeyView",
    # "ff_environment_edit",
    # "ff_environment_targetGroupEdit",
    # "ff_environment_view",
    # "ff_featureflag_delete",
    # "ff_featureflag_edit",
    # "ff_featureflag_toggle",
    # "ff_featureflag_view",
    # "ff_target_view",
    # "ff_targetgroup_delete",
    # "ff_targetgroup_edit",
    # "ff_targetgroup_view",

    "gitops_agent_delete",
    "gitops_agent_edit",
    "gitops_agent_view",
    "gitops_application_delete",
    "gitops_application_edit",
    "gitops_application_sync",
    "gitops_application_view",
    "gitops_cert_delete",
    "gitops_cert_edit",
    "gitops_cert_view",
    "gitops_cluster_delete",
    "gitops_cluster_edit",
    "gitops_cluster_view",
    "gitops_gpgkey_delete",
    "gitops_gpgkey_edit",
    "gitops_gpgkey_view",
    "gitops_repository_delete",
    "gitops_repository_edit",
    "gitops_repository_view",

    # "iac_workspace_accessstate",
    # "iac_workspace_approve",
    # "iac_workspace_delete",
    # "iac_workspace_deletevariable",
    # "iac_workspace_edit",
    # "iac_workspace_editvariable",
    # "iac_workspace_view",

    # "idp_advancedconfiguration_delete",
    # "idp_advancedconfiguration_edit",
    # "idp_advancedconfiguration_view",
    # "idp_catalogaccesspolicy_create",
    # "idp_catalogaccesspolicy_delete",
    # "idp_catalogaccesspolicy_edit",
    # "idp_catalogaccesspolicy_view",
    # "idp_integration_create",
    # "idp_integration_delete",
    # "idp_integration_edit",
    # "idp_integration_view",
    # "idp_layout_edit",
    # "idp_layout_view",
    # "idp_plugin_delete",
    # "idp_plugin_edit",
    # "idp_plugin_toggle",
    # "idp_plugin_view",
    # "idp_scorecard_delete",
    # "idp_scorecard_edit",
    # "idp_scorecard_view",

    # "servicediscovery_networkmap_create",
    # "servicediscovery_networkmap_delete",
    # "servicediscovery_networkmap_edit",
    # "servicediscovery_networkmap_view",

    # "ssca_enforcementexemption_delete",
    # "ssca_enforcementexemption_edit",
    # "ssca_enforcementexemption_review",
    # "ssca_enforcementexemption_view",
    # "ssca_remediationtracker_close",
    # "ssca_remediationtracker_edit",
    # "ssca_remediationtracker_view",

    # "sto_exemption_approve",
    # "sto_exemption_create",
    # "sto_exemption_view",
    # "sto_issue_view",
    # "sto_scan_view",
    # "sto_testtarget_edit",
    # "sto_testtarget_view",
    # "sto_ticket_delete",
    # "sto_ticket_edit",
    # "sto_ticket_view",
  ]
  allowed_scope_levels = ["account"]
}

resource "harness_platform_roles" "release_manager" {
  identifier  = "release_manager"
  name        = "release-manager"
  description = "An example role managed by Terraform."
  tags        = concat(var.default_tags, ["Demo:true"])
  permissions = [
    # "ccm_anomalies_view",
    # "ccm_autoStoppingRule_delete",
    # "ccm_autoStoppingRule_edit",
    # "ccm_autoStoppingRule_view",
    # "ccm_budget_delete",
    # "ccm_budget_edit",
    # "ccm_budget_view",
    # "ccm_cloudAssetGovernanceEnforcement_delete",
    # "ccm_cloudAssetGovernanceEnforcement_edit",
    # "ccm_cloudAssetGovernanceEnforcement_view",
    # "ccm_cloudAssetGovernanceRule_delete",
    # "ccm_cloudAssetGovernanceRule_edit",
    # "ccm_cloudAssetGovernanceRule_execute",
    # "ccm_cloudAssetGovernanceRule_view",
    # "ccm_cloudAssetGovernanceRuleSet_delete",
    # "ccm_cloudAssetGovernanceRuleSet_edit",
    # "ccm_cloudAssetGovernanceRuleSet_view",
    # "ccm_commitmentOrchestrator_edit",
    # "ccm_commitmentOrchestrator_view",
    # "ccm_costCategory_delete",
    # "ccm_costCategory_edit",
    # "ccm_costCategory_view",
    # "ccm_currencyPreference_edit",
    # "ccm_currencyPreference_view",
    # "ccm_folder_delete",
    # "ccm_folder_edit",
    # "ccm_folder_view",
    # "ccm_loadBalancer_delete",
    # "ccm_loadBalancer_edit",
    # "ccm_loadBalancer_view",
    # "ccm_overview_view",
    # "ccm_perspective_delete",
    # "ccm_perspective_edit",
    # "ccm_perspective_view",
    # "ccm_recommendations_view",

    # "cet_agents_view",
    # "cet_criticalevent_create",
    # "cet_criticalevent_delete",
    # "cet_criticalevent_view",
    # "cet_token_create",
    # "cet_token_revoke",
    # "cet_token_view",

    # "chaos_chaosexperiment_delete",
    # "chaos_chaosexperiment_edit",
    # "chaos_chaosexperiment_execute",
    # "chaos_chaosexperiment_view",
    # "chaos_chaosgameday_delete",
    # "chaos_chaosgameday_edit",
    # "chaos_chaosgameday_view",
    # "chaos_chaoshub_delete",
    # "chaos_chaoshub_edit",
    # "chaos_chaoshub_view",
    # "chaos_chaosinfrastructure_delete",
    # "chaos_chaosinfrastructure_edit",
    # "chaos_chaosinfrastructure_view",
    # "chaos_chaossecuritygovernance_delete",
    # "chaos_chaossecuritygovernance_edit",
    # "chaos_chaossecuritygovernance_view",

    # "chi_downtime_delete",
    # "chi_downtime_edit",
    # "chi_downtime_view",
    # "chi_monitoredservice_delete",
    # "chi_monitoredservice_edit",
    # "chi_monitoredservice_toggle",
    # "chi_monitoredservice_view",
    # "chi_slo_delete",
    # "chi_slo_edit",
    # "chi_slo_view",

    # "code_repo_delete",
    # "code_repo_edit",
    # "code_repo_push",
    # "code_repo_reportCommitCheck",
    # "code_repo_view",

    # "core_account_edit",
    # "core_account_view",
    # "core_audit_view",
    # "core_authsetting_delete",
    # "core_authsetting_edit",
    # "core_authsetting_view",
    "core_connector_access",
    # "core_connector_delete",
    # "core_connector_edit",
    # "core_connector_view",
    # "core_dashboards_edit",
    # "core_dashboards_view",
    # "core_delegate_delete",
    # "core_delegate_edit",
    # "core_delegate_view",
    # "core_delegateconfiguration_delete",
    # "core_delegateconfiguration_edit",
    # "core_delegateconfiguration_view",
    "core_deploymentfreeze_global",
    "core_deploymentfreeze_manage",
    "core_deploymentfreeze_override",
    "core_environment_access",
    # "core_environment_delete",
    # "core_environment_edit",
    # "core_environment_rollback",
    # "core_environment_view",
    "core_environmentgroup_access",
    # "core_environmentgroup_delete",
    # "core_environmentgroup_edit",
    # "core_environmentgroup_view",
    "core_file_access",
    # "core_file_delete",
    # "core_file_edit",
    # "core_file_view",
    # "core_gitxWebhooks_delete",
    # "core_gitxWebhooks_edit",
    # "core_gitxWebhooks_view",
    # "core_governancePolicy_create",
    # "core_governancePolicy_delete",
    # "core_governancePolicy_edit",
    # "core_governancePolicy_view",
    # "core_governancePolicySets_create",
    # "core_governancePolicySets_delete",
    # "core_governancePolicySets_edit",
    # "core_governancePolicySets_evaluate",
    # "core_governancePolicySets_view",
    # "core_inputset_delete",
    # "core_inputset_edit",
    # "core_inputset_view",
    # "core_license_edit",
    # "core_license_view",
    # "core_organization_create",
    # "core_organization_delete",
    # "core_organization_edit",
    "core_organization_view",
    # "core_pipeline_delete",
    # "core_pipeline_edit",
    "core_pipeline_execute",
    "core_pipeline_view",
    # "core_project_create",
    # "core_project_delete",
    # "core_project_edit",
    "core_project_view",
    # "core_resourcegroup_delete",
    # "core_resourcegroup_edit",
    # "core_resourcegroup_view",
    # "core_role_delete",
    # "core_role_edit",
    # "core_role_view",
    "core_secret_access",
    # "core_secret_delete",
    # "core_secret_edit",
    # "core_secret_view",
    "core_service_access",
    # "core_service_delete",
    # "core_service_edit",
    # "core_service_view",
    # "core_serviceaccount_delete",
    # "core_serviceaccount_edit",
    # "core_serviceaccount_list",
    # "core_serviceaccount_manageapikey",
    # "core_serviceaccount_view",
    # "core_setting_edit",
    # "core_setting_view",
    # "core_smtp_delete",
    # "core_smtp_edit",
    # "core_smtp_view",
    # "core_streamingDestination_delete",
    # "core_streamingDestination_edit",
    # "core_streamingDestination_view",
    "core_template_access",
    # "core_template_copy",
    # "core_template_delete",
    # "core_template_edit",
    # "core_template_view",
    # "core_user_invite",
    # "core_user_manage",
    # "core_user_view",
    # "core_usergroup_manage",
    # "core_usergroup_view",
    # "core_variable_delete",
    # "core_variable_edit",
    # "core_variable_view",

    # "ff_environment_apiKeyCreate",
    # "ff_environment_apiKeyDelete",
    # "ff_environment_apiKeyView",
    # "ff_environment_edit",
    # "ff_environment_targetGroupEdit",
    "ff_environment_view",
    # "ff_featureflag_delete",
    # "ff_featureflag_edit",
    "ff_featureflag_toggle",
    "ff_featureflag_view",
    "ff_target_view",
    # "ff_targetgroup_delete",
    # "ff_targetgroup_edit",
    "ff_targetgroup_view",

    # "gitops_agent_delete",
    # "gitops_agent_edit",
    # "gitops_agent_view",
    # "gitops_application_delete",
    # "gitops_application_edit",
    # "gitops_application_sync",
    # "gitops_application_view",
    # "gitops_cert_delete",
    # "gitops_cert_edit",
    # "gitops_cert_view",
    # "gitops_cluster_delete",
    # "gitops_cluster_edit",
    # "gitops_cluster_view",
    # "gitops_gpgkey_delete",
    # "gitops_gpgkey_edit",
    # "gitops_gpgkey_view",
    # "gitops_repository_delete",
    # "gitops_repository_edit",
    # "gitops_repository_view",

    # "iac_workspace_accessstate",
    # "iac_workspace_approve",
    # "iac_workspace_delete",
    # "iac_workspace_deletevariable",
    # "iac_workspace_edit",
    # "iac_workspace_editvariable",
    # "iac_workspace_view",

    # "idp_advancedconfiguration_delete",
    # "idp_advancedconfiguration_edit",
    # "idp_advancedconfiguration_view",
    # "idp_catalogaccesspolicy_create",
    # "idp_catalogaccesspolicy_delete",
    # "idp_catalogaccesspolicy_edit",
    # "idp_catalogaccesspolicy_view",
    # "idp_integration_create",
    # "idp_integration_delete",
    # "idp_integration_edit",
    # "idp_integration_view",
    # "idp_layout_edit",
    # "idp_layout_view",
    # "idp_plugin_delete",
    # "idp_plugin_edit",
    # "idp_plugin_toggle",
    # "idp_plugin_view",
    # "idp_scorecard_delete",
    # "idp_scorecard_edit",
    # "idp_scorecard_view",

    # "servicediscovery_networkmap_create",
    # "servicediscovery_networkmap_delete",
    # "servicediscovery_networkmap_edit",
    # "servicediscovery_networkmap_view",

    # "ssca_enforcementexemption_delete",
    # "ssca_enforcementexemption_edit",
    # "ssca_enforcementexemption_review",
    # "ssca_enforcementexemption_view",
    # "ssca_remediationtracker_close",
    # "ssca_remediationtracker_edit",
    # "ssca_remediationtracker_view",

    "sto_exemption_approve",
    # "sto_exemption_create",
    "sto_exemption_view",
    "sto_issue_view",
    "sto_scan_view",
    # "sto_testtarget_edit",
    "sto_testtarget_view",
    # "sto_ticket_delete",
    # "sto_ticket_edit",
    "sto_ticket_view",
  ]
  allowed_scope_levels = ["account"]
}
